# Generated by Django 4.2.23 on 2025-09-01 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eco_users', '0002_driver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rider',
            new_name='customer',
        ),
    ]
